version: '3.9'
services:
  opentrashmail:
    image: 'opentrashmail:latest'
    restart: always
    volumes:
      - './data:/var/www/opentrashmail/data'
      - './logs:/var/www/opentrashmail/logs'
    environment:
      - URL=http://localhost:8080
      - DOMAINS=fakedomain.com
      - DATEFORMAT=D.M.YYYY HH:mm
      - SKIP_FILEPERMISSIONS=false
      - DISCARD_UNKNOWN=false
      - ADMIN=admin@mail.com
      - ADMIN_ENABLED=true
      #- ADMIN_PASSWORD=dummy_password_to_replace
      - SHOW_ACCOUNT_LIST=true
      - SHOW_LOGS=true
      #-PASSWORD=qwerty##2023
      # - ALLOWED_IPS=192.168.0.0/16,2a02:ab:cd:ef::/60
      # - ATTACHMENTS_MAX_SIZE=10000000
      - MAILPORT_TLS=465
      - TLS_CERTIFICATE=certs/cert.pem
      - TLS_PRIVATE_KEY=certs/key.pem

    ports:
      - '2525:25'
      - '587:25'
      - '465:465'
      - '8080:80'
